---
# SPDX-FileCopyrightText: 2025 Tymoteusz Blazejczyk <tymoteusz.blazejczyk@tymonx.com>
# SPDX-License-Identifier: Apache-2.0

deploy-pypi-public:
    image: python:latest
    rules:
        - if: $CI_COMMIT_TAG
          when: always
        - when: never
    script:
        - pip install --upgrade pip
        - pip install build twine
        - python -m build
        - python -m twine upload dist/*

deploy-pypi-gitlab:
    image: python:latest
    variables:
        TWINE_USERNAME: gitlab-ci-token
        TWINE_PASSWORD: $CI_JOB_TOKEN
    rules:
        - if: $CI_COMMIT_TAG || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
          when: always
        - when: never
    script:
        - pip install --upgrade pip
        - pip install build twine
        - python -m build
        - python -m twine upload --repository-url "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi" dist/*
